spring:
  main:
    banner-mode: off
  application:
    name: translator-bot

lingvo:
  api:
    key: ${API-KEY}
    srcLang: 1033
    dstLang: 1049

bot:
  name: EnglishWordTranslatorBot
  token: ${BOT-TOKEN}

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.cloud.config.client: debug
