lingvo:
  api:
    key: ${API-KEY}
    srcLang: 1033
    dstLang: 1049

bot:
  name: EnglishWordTranslatorBot
  token: ${BOT-TOKEN}

server:
  port: 8080
---
logging:
  level:
    com:
      gmail:
        arthurstrokov:
          translatorbot:
            gateway:
              TranslatorBotFeignClient: debug
---
feign:
  client:
    config:
      default:
        errorDecoder: com.gmail.arthurstrokov.translatorbot.configuration.RetreiveMessageErrorDecoder
        loggerLevel: basic
